seed:
  42
original_svd: true
pretrained_model_path: "./ckpt/pretrained/stable-video-diffusion-img2vid/"
batch_size: 1
data_dir:
  ./demo
resolution: 
  - 1024
  - 576
checkpoint_root: None
step:
  20000
use_ema: true
motion_bucket_id:
  20.0
fps:
  3
num_step:
  25
sigma_max:
  100
analytic_path:
  "./ckpt/initial_noise_1024.pt"
