seed:
  42
debug: false
original_svd: false
pretrained_model_path: "./ckpt/pretrained/stable-video-diffusion-img2vid/"
batch_size: 1
data_dir:
  ./demo
resolution: 
  - 512
  - 320
checkpoint_root:
  ./ckpt/finetuned
step:
  20000
use_ema: true
motion_bucket_id:
  20.0
fps:
  5
num_step:
  25
noise_aug_strength:
  0
sigma_max:
  100
analytic_path:
  ./ckpt/initial_noise_512.pt"